#!/usr/bin/env python3
"""Create a provenance-first inventory of global food-composition sources.

This utility deliberately performs no food or component matching and creates
no training matrix.  It snapshots directly downloadable source files in their
original formats, records unavailable/restricted sources explicitly, and
writes a machine-readable source registry for the accompanying landscape
review.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "raw" / "global_fcdb_inventory_2026_09_10"
DOWNLOAD_DIR = OUT_DIR / "downloads"


def source(**kwargs: Any) -> dict[str, Any]:
    """Build a registry entry and make deliberately omitted fields explicit."""
    required = {
        "source_key",
        "name",
        "region",
        "countries_or_coverage",
        "scope",
        "data_kind",
        "reported_foods",
        "reported_components",
        "measurement_provenance",
        "access_status",
        "license_or_terms",
        "foundation_model_role",
        "suitability",
        "limitations",
        "official_url",
        "download_url",
        "local_raw_path",
    }
    missing = required - set(kwargs)
    if missing:
        raise ValueError(f"Incomplete source registry entry: {sorted(missing)}")
    return kwargs


# Facts in this registry are sourced from each official landing page named in
# official_url.  Unknown counts stay unknown rather than being estimated.
SOURCES = [
    source(
        source_key="usda_foundation",
        name="USDA FoodData Central Foundation Foods",
        region="North America",
        countries_or_coverage="United States; analytically characterized reference foods",
        scope="national_core",
        data_kind="quantitative nutrients and selected chemical constituents",
        reported_foods="395 (local frozen export used by this project)",
        reported_components="235 observed axes in the local frozen export",
        measurement_provenance="USDA Foundation Foods documentation and sample/analytical metadata",
        access_status="already_local",
        license_or_terms="United States public-domain government data",
        foundation_model_role="high-quality source-holdout / external validation candidate",
        suitability="high: explicit analytical context and independent-source evaluation value",
        limitations="Small compared with national tables; must remain a source-holdout when used for external validation.",
        official_url="https://fdc.nal.usda.gov/data-documentation.html",
        download_url="https://fdc.nal.usda.gov/download-datasets.html",
        local_raw_path="data/raw/usda/foundation_2026_04_30",
    ),
    source(
        source_key="usda_sr_legacy",
        name="USDA National Nutrient Database for Standard Reference, Legacy Release",
        region="North America",
        countries_or_coverage="United States",
        scope="national_core",
        data_kind="quantitative nutrients, fatty acids, amino acids and selected other components",
        reported_foods="7,793 (local project audit)",
        reported_components="149 observed nutrient axes in the local project audit",
        measurement_provenance="Compiled USDA reference database; value-level source type varies",
        access_status="already_local",
        license_or_terms="United States public-domain government data",
        foundation_model_role="large core pretraining source, subject to record-level provenance filtering",
        suitability="high for coverage; medium for value-level analytical uniformity",
        limitations="Legacy release; food values have heterogeneous compilation histories and overlap with newer USDA products.",
        official_url="https://fdc.nal.usda.gov/data-documentation.html",
        download_url="https://fdc.nal.usda.gov/download-datasets.html",
        local_raw_path="data/raw/usda/sr_legacy_2018",
    ),
    source(
        source_key="cnf",
        name="Canadian Nutrient File",
        region="North America",
        countries_or_coverage="Canada",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="5,993 (local project audit)",
        reported_components="173 axes in the local project audit",
        measurement_provenance="Health Canada compiled national database; value-level source type varies",
        access_status="already_local",
        license_or_terms="Open Government Licence - Canada",
        foundation_model_role="core regional pretraining source and North-American generalization panel",
        suitability="high for legal reuse and nutrient coverage",
        limitations="Some values derive from borrowed, imputed or calculated sources; do not treat every row as an independent laboratory measurement.",
        official_url="https://food-nutrition.canada.ca/cnf-fce/",
        download_url="https://food-nutrition.canada.ca/cnf-fce/",
        local_raw_path="data/raw/cnf_2026",
    ),
    source(
        source_key="usda_fndds_2021_2023",
        name="USDA Food and Nutrient Database for Dietary Studies (FNDDS), 2021-2023",
        region="North America",
        countries_or_coverage="United States; foods and mixed dishes used for dietary-survey coding",
        scope="calculated_dish_auxiliary",
        data_kind="quantitative nutrients, input-food links and derivation metadata",
        reported_foods="5,432 food records in the locally retained 2024-10-31 export",
        reported_components="477 nutrient definitions; 353,015 food-nutrient rows in the local export",
        measurement_provenance="USDA dietary-survey database; values may be calculated from ingredient/recipe links and derivation records",
        access_status="already_local",
        license_or_terms="United States public-domain government data",
        foundation_model_role="auxiliary recipe/mixed-dish layer, not an independent primary validation source",
        suitability="high for culinary and mixed-dish coverage; unsuitable as a substitute for direct analytical food labels",
        limitations="Many profiles are recipe-derived or otherwise connected to USDA reference data. Keep derivation and input-food links and do not count them as independent observations when evaluating generalization.",
        official_url="https://fdc.nal.usda.gov/data-documentation.html",
        download_url="https://fdc.nal.usda.gov/download-datasets.html",
        local_raw_path="data/raw/usda/fndds_2021_2023",
    ),
    source(
        source_key="ciqual_2025",
        name="ANSES-Ciqual French Food Composition Table 2025",
        region="Europe",
        countries_or_coverage="France",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="3,482 food rows in the locally retained 2025 Excel table",
        reported_components="75 INFOODS code rows in the locally retained workbook",
        measurement_provenance="ANSES compilation with source reference and quality information documented by component/food",
        access_status="already_local",
        license_or_terms="CC BY 4.0",
        foundation_model_role="core European pretraining source",
        suitability="high: open structured release, explicit food/component provenance framework",
        limitations="Excel download does not include every source detail; preserve accompanying XML and source files.",
        official_url="https://ciqual.anses.fr/",
        download_url="https://doi.org/10.5281/zenodo.17550133",
        local_raw_path="data/raw/candidates/ciqual_2025",
    ),
    source(
        source_key="frida_6_1",
        name="Frida FoodData 6.1",
        region="Europe",
        countries_or_coverage="Denmark",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="1,388 food rows in the local Data_Table sheet after workbook heading rows",
        reported_components="approximately 230 analyte columns in the local Data_Table sheet",
        measurement_provenance="National Food Institute food-data system with documented references",
        access_status="already_local",
        license_or_terms="CC BY 4.0",
        foundation_model_role="core European pretraining source",
        suitability="high: open, structured, national food data",
        limitations="Compilation and calculation methods vary by value; retain source/reference metadata.",
        official_url="https://frida.fooddata.dk/",
        download_url="https://doi.org/10.11583/DTU.32312844.v1",
        local_raw_path="data/raw/candidates/frida_6_1",
    ),
    source(
        source_key="cofid_2021",
        name="UK Composition of Foods Integrated Dataset 2021",
        region="Europe",
        countries_or_coverage="United Kingdom",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="approximately 2,888 data rows across the local CoFID data sheets",
        reported_components="varies by CoFID table; nutrient panels are distributed over separate sheets",
        measurement_provenance="UK national compiled food composition data",
        access_status="already_local",
        license_or_terms="UK Open Government Licence",
        foundation_model_role="core European pretraining source",
        suitability="high for reproducible nutrient benchmarking",
        limitations="Values have mixed analytical, calculated and borrowed provenance; source flags must survive later construction.",
        official_url="https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid",
        download_url="https://www.gov.uk/government/publications/composition-of-foods-integrated-dataset-cofid",
        local_raw_path="data/raw/candidates/cofid_2021",
    ),
    source(
        source_key="fineli",
        name="Fineli Finnish Food Composition Database",
        region="Europe",
        countries_or_coverage="Finland",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="4,232 foods in official open-data package",
        reported_components="55 components in package 1; 74 in package 2",
        measurement_provenance="Finnish Institute for Health and Welfare compiled database",
        access_status="official_download_available_but_automated_mirror_blocked",
        license_or_terms="THL open-data licence and disclaimer",
        foundation_model_role="core European pretraining source after manual snapshot download",
        suitability="high: official CSV packages and API; broad Finnish food coverage",
        limitations="This collection run encountered Cloudflare HTTP 403; record the version and manually download through the official portal before model use.",
        official_url="https://fineli.fi/fineli/en/avoin-data",
        download_url="https://fineli.fi/fineli/en/avoin-data",
        local_raw_path="",
    ),
    source(
        source_key="norwegian_fcdb",
        name="Norwegian Food Composition Database",
        region="Europe",
        countries_or_coverage="Norway",
        scope="national_core",
        data_kind="quantitative nutrient composition and food metadata",
        reported_foods="2,121 foods in the locally retained API snapshot",
        reported_components="57 nutrients in the locally retained API snapshot",
        measurement_provenance="Norwegian national database API exposes source records and LanguaL metadata",
        access_status="already_local",
        license_or_terms="licence must be confirmed from the current official terms before redistribution",
        foundation_model_role="core European source after licence and value-level source audit",
        suitability="high data-accessibility value; medium pending terms review",
        limitations="The current repository snapshot was retained as evidence only; do not redistribute or train until licence and source-value status are approved.",
        official_url="https://www.matvaretabellen.no/en/api/",
        download_url="https://www.matvaretabellen.no/api/en/foods.json",
        local_raw_path="data/raw/expansion_2026_09_06/norway",
    ),
    source(
        source_key="nevo_2025_9",
        name="Dutch Food Composition Database (NEVO-online 2025/9.0)",
        region="Europe",
        countries_or_coverage="Netherlands",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="2,328",
        reported_components="approximately 130 nutrients",
        measurement_provenance="RIVM national database with source reference per value",
        access_status="free_download_requires_acceptance_of_terms",
        license_or_terms="CC BY 4.0, subject to dataset agreement/copyright and disclaimer",
        foundation_model_role="strong core European source after term acceptance and version snapshot",
        suitability="high: official database, food-level source information, broad nutrient panel",
        limitations="Requires terms acceptance; values include analysis, labels, foreign tables and recipe estimates, so later admission must use value-level source type.",
        official_url="https://www.rivm.nl/en/dutch-food-composition-database",
        download_url="https://www.rivm.nl/en/dutch-food-composition-database/use-of-nevo-online/request-dataset",
        local_raw_path="",
    ),
    source(
        source_key="swiss_fcdb_7_1",
        name="Swiss Food Composition Database 7.1",
        region="Europe",
        countries_or_coverage="Switzerland",
        scope="national_core",
        data_kind="quantitative nutrients with source workbook",
        reported_foods="1,216 generic food rows; 230 branded-product rows in downloaded workbook",
        reported_components="144 columns in food sheets; component code sheet included",
        measurement_provenance="Swiss Federal Office of Public Health database with source table",
        access_status="downloaded_new",
        license_or_terms="free use, including scientific and commercial use, with source acknowledgement",
        foundation_model_role="core European source; generic-food table preferred over branded-product table",
        suitability="high: current Excel release with component and source metadata",
        limitations="Keep branded products separate from generic foods; source type may be analytical, calculated or manufacturer-derived.",
        official_url="https://valeursnutritives.ch/en/downloads/",
        download_url="https://naehrwertdaten.ch/wp-content/uploads/2026/07/Base_de_donnees_suisse_des_valeurs_nutritives.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/swiss_fcdb_v7_1.xlsx",
    ),
    source(
        source_key="bls_4_0",
        name="German Nutrient Database BLS 4.0 (2025)",
        region="Europe",
        countries_or_coverage="Germany",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="7,140 food records in the locally retained BLS 4.0 archive",
        reported_components="138 official component rows in the locally retained BLS 4.0 archive",
        measurement_provenance="German national nutrient database",
        access_status="already_local_terms_review_required",
        license_or_terms="current licence must be reviewed before training-data redistribution",
        foundation_model_role="candidate core European source after legal and provenance audit",
        suitability="medium-high: large current national source; not yet licence-cleared in this project",
        limitations="Existing download is retained as evidence only; no training admission in this inventory.",
        official_url="https://blsdb.de/download",
        download_url="https://blsdb.de/download",
        local_raw_path="data/raw/expansion_evidence_2026_09_07/bls",
    ),
    source(
        source_key="efsa_eu_fcdb_2026",
        name="EFSA Open Access European Food Composition Database",
        region="Europe",
        countries_or_coverage="At least 16 EU, EFTA and pre-accession national databases",
        scope="regional_harmonized",
        data_kind="quantitative nutrient composition",
        reported_foods="approximately 28,000 food commodities",
        reported_components="not stated as a single count on the landing page",
        measurement_provenance="EFSA harmonized national submissions mapped to FoodEx2",
        access_status="official_open_access_landing_page_data_download_route_to_be_confirmed",
        license_or_terms="open access claimed by EFSA; release-specific terms and bulk endpoint require confirmation",
        foundation_model_role="high-priority European expansion source; use only after checking lineage against constituent national datasets",
        suitability="high geographic reach; medium incremental-evidence value because it may reproduce national data already collected",
        limitations="Do not count it as independent evidence from Ciqual/Fineli/NEVO/etc.; deduplicate by original provider and provenance before any future construction.",
        official_url="https://www.efsa.europa.eu/en/data-report/food-composition",
        download_url="https://www.efsa.europa.eu/en/data-report/food-composition",
        local_raw_path="",
    ),
    source(
        source_key="afcd_release_3",
        name="Australian Food Composition Database Release 3",
        region="Oceania",
        countries_or_coverage="Australia",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="1,588",
        reported_components="58 nutrients",
        measurement_provenance="Food Standards Australia New Zealand national release; primarily laboratory analyses",
        access_status="already_local",
        license_or_terms="CC BY-SA 3.0 AU",
        foundation_model_role="core Oceania source and independent regional evaluation candidate",
        suitability="high: current official structured release with food, nutrient and reference workbooks",
        limitations="Includes recipes and calculated values; later construction must distinguish them from direct analytical food profiles.",
        official_url="https://www.foodstandards.gov.au/science-data/food-nutrient-databases/afcd/data-files",
        download_url="https://www.foodstandards.gov.au/science-data/food-nutrient-databases/afcd/data-files",
        local_raw_path="data/raw/expansion_2026_09_06/afcd",
    ),
    source(
        source_key="foodfiles_2024",
        name="New Zealand FOODfiles 2024",
        region="Oceania",
        countries_or_coverage="New Zealand",
        scope="national_core",
        data_kind="quantitative nutrients and extended components",
        reported_foods="2,857",
        reported_components="87 standard components; up to 434 in unabridged files",
        measurement_provenance="New Zealand Institute for Public Health and Forensic Science compilation",
        access_status="already_local_terms_review_required",
        license_or_terms="terms of use require review/acceptance",
        foundation_model_role="high-value Oceania expansion source after licence approval",
        suitability="high coverage and component breadth; conditional legal reuse",
        limitations="Keep source/recipe/calculated indicators; current local acquisition has not been admitted for training.",
        official_url="https://www.foodcomposition.co.nz/foodfiles",
        download_url="https://www.foodcomposition.co.nz/foodfiles",
        local_raw_path="data/raw/expansion_2026_09_06/foodfiles",
    ),
    source(
        source_key="pacific_pndb_2020",
        name="Pacific Nutrient Database 2020",
        region="Oceania",
        countries_or_coverage="Pacific Island countries and territories",
        scope="regional_nutrient_database",
        data_kind="nutrition-related food composition information",
        reported_foods="not stated on the public catalogue page",
        reported_components="not stated on the public catalogue page",
        measurement_provenance="Pacific Community nutrient database for food-security tools",
        access_status="public_catalogue_download_blocked_in_this_collection_run",
        license_or_terms="terms not confirmed in this inventory",
        foundation_model_role="important regional-coverage candidate after an official bulk snapshot and provenance audit",
        suitability="medium: substantially improves Pacific coverage but needs data and licence inspection",
        limitations="The available file route returned HTTP 403 to automated retrieval; it must not be treated as an established independent analytical source until raw documentation is obtained.",
        official_url="https://microdata.pacificdata.org/index.php/catalog/755/get-microdata",
        download_url="https://microdata.pacificdata.org/index.php/catalog/770/download/4112",
        local_raw_path="",
    ),
    source(
        source_key="mext_japan_2023",
        name="Japan Standard Tables of Food Composition 2020, Eighth Revised Edition and 2023 Supplement",
        region="Asia",
        countries_or_coverage="Japan",
        scope="national_core",
        data_kind="quantitative nutrients and food constituents",
        reported_foods="not re-counted in this inventory; official Excel sections locally available",
        reported_components="not re-counted in this inventory",
        measurement_provenance="Japanese Ministry of Education, Culture, Sports, Science and Technology national standard tables",
        access_status="already_local",
        license_or_terms="official site permits use with required citation; release-specific conditions retained locally",
        foundation_model_role="core East-Asian source",
        suitability="high: authoritative national table with structured Excel distributions",
        limitations="Japanese-language current release needs careful translation and component-definition audit; do not mix analytical and calculated values without flags.",
        official_url="https://www.mext.go.jp/a_menu/syokuhinseibun/index.htm",
        download_url="https://fooddb.mext.go.jp/",
        local_raw_path="data/raw/expansion_2026_09_06/mext",
    ),
    source(
        source_key="kfind_korea",
        name="K-FIND Korean Food and Nutrient Database",
        region="Asia",
        countries_or_coverage="Republic of Korea",
        scope="national_core",
        data_kind="quantitative food nutrient data",
        reported_foods="not stated on public landing page",
        reported_components="not stated on public landing page",
        measurement_provenance="Korean Ministry of Food and Drug Safety database with source and data-generation fields",
        access_status="official_bulk_download_and_api_advertised_manual_access_required",
        license_or_terms="Korean public-data portal reports no use restriction for an API; bulk download terms need snapshot confirmation",
        foundation_model_role="priority East-Asian source",
        suitability="high potential: active national maintenance, stated bulk download and open API",
        limitations="The public UI documents downloads but no stable unauthenticated bulk endpoint was recovered in this collection run; capture a versioned official file/API export before use.",
        official_url="https://www.foodsafetykorea.go.kr/fcdb/simple/search/firstList.do",
        download_url="https://www.data.go.kr/data/15127578/openapi.do",
        local_raw_path="",
    ),
    source(
        source_key="taiwan_tfda",
        name="Taiwan Food and Drug Administration Nutrition Information Database",
        region="Asia",
        countries_or_coverage="Taiwan",
        scope="national_core",
        data_kind="quantitative nutrient composition with sample size and standard deviation fields",
        reported_foods="not stated on the data catalogue page",
        reported_components="not stated on the data catalogue page",
        measurement_provenance="TFDA public dataset contains food category, sample description, analyte, unit, per-100-g value, sample size and standard deviation",
        access_status="official_csv_json_xml_download_advertised_endpoint_changed",
        license_or_terms="Taiwan Open Government Data License v1.0",
        foundation_model_role="high-priority East-Asian core source",
        suitability="high: official open licence and unusually useful sample/SD metadata",
        limitations="The former direct endpoint now resolves to Swagger UI; obtain the current dataset resource URL from the catalogue rather than scrape the user interface.",
        official_url="https://data.gov.tw/en/datasets/8543",
        download_url="https://data.fda.gov.tw/opendata/exportDataList.do?method=openDataApi&InfoId=20",
        local_raw_path="",
    ),
    source(
        source_key="thai_fcd_2025",
        name="Thai Food Composition Database Online Version 3 (2025)",
        region="Asia",
        countries_or_coverage="Thailand",
        scope="national_core",
        data_kind="quantitative nutrients and food composition",
        reported_foods="not stated on public landing page",
        reported_components="not stated on public landing page",
        measurement_provenance="INMU/ASEANFOODS compilation; newly analysed data mainly from INMU laboratories, integrated with previous FCT editions and reviewed to FAO/INFOODS guidance",
        access_status="searchable_web_tool_no_bulk_export_found",
        license_or_terms="free non-commercial access with acknowledgement; further reproduction/distribution may require permission",
        foundation_model_role="priority Thai/ASEAN source after permission and bulk export",
        suitability="high scientific provenance; conditional data/reuse access",
        limitations="No bulk machine-readable export found; cannot enter a reproducible model corpus until the curator grants data access and terms.",
        official_url="https://inmu.mahidol.ac.th/thaifcd/",
        download_url="https://inmu.mahidol.ac.th/thaifcd/home",
        local_raw_path="",
    ),
    source(
        source_key="ifct_2017",
        name="Indian Food Composition Tables 2017",
        region="Asia",
        countries_or_coverage="India",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="586",
        reported_components="not re-counted in this inventory",
        measurement_provenance="Indian Council of Medical Research/National Institute of Nutrition table",
        access_status="already_local_pdf_only",
        license_or_terms="reuse and machine-extraction terms require confirmation",
        foundation_model_role="important South-Asian source after authoritative machine-readable release or permission",
        suitability="medium-high for geographic coverage; low current ingestion readiness",
        limitations="Current official artifact is a PDF; no validated, machine-readable value export has been admitted.",
        official_url="https://www.icmr.gov.in/icmrobject/custom_data/1703247749_icmr_7.pdf",
        download_url="https://www.icmr.gov.in/icmrobject/custom_data/1703247749_icmr_7.pdf",
        local_raw_path="data/raw/expansion_2026_09_06/ifct/IFCT2017_official.pdf",
    ),
    source(
        source_key="bangladesh_fct_2013",
        name="Food Composition Table for Bangladesh 2013",
        region="Asia",
        countries_or_coverage="Bangladesh",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="381 user-table food codes in the downloaded workbook; auxiliary rows preserve SD/range, n and recipe information",
        reported_components="244 component rows in the downloaded Components sheet",
        measurement_provenance="University of Dhaka/FAO-INFOODS-linked national food composition table",
        access_status="downloaded_new",
        license_or_terms="official FAO-hosted workbook; release-specific reuse terms require documentation review",
        foundation_model_role="South-Asian source candidate",
        suitability="medium-high: official machine-readable national table, subject to currentness and value-level source review",
        limitations="2013 release; national table may include calculated/borrowed values that must remain labelled in a later dataset.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/FCDB_7_4_14.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/bangladesh_fct_2013.xlsx",
    ),
    source(
        source_key="smiling_cambodia_2013",
        name="SMILING Food Composition Table for Cambodia 2013",
        region="Asia",
        countries_or_coverage="Cambodia",
        scope="national_core_quality_annotated",
        data_kind="quantitative nutrient composition plus value-level references and quality assessment",
        reported_foods="90",
        reported_components="not re-counted in this inventory",
        measurement_provenance="SMILING project table A has value references; table B carries value-level quality assessment",
        access_status="downloaded_new",
        license_or_terms="FAO-hosted workbook; project/reuse conditions need verification",
        foundation_model_role="small, high-documentation Southeast-Asian supplement",
        suitability="medium: strong provenance design but small food count and 2013 release",
        limitations="A quality-assessed source table is not automatically independent of regional sources; preserve both paired workbooks and check original references.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT__Cambodia_010813_protected.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_cambodia_values.xlsx; data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_cambodia_quality.xlsx",
    ),
    source(
        source_key="smiling_indonesia_2013",
        name="SMILING Food Composition Table for Indonesia 2013",
        region="Asia",
        countries_or_coverage="Indonesia",
        scope="national_core_quality_annotated",
        data_kind="quantitative nutrient composition plus value-level references and quality assessment",
        reported_foods="174",
        reported_components="not re-counted in this inventory",
        measurement_provenance="SMILING project table A has value references; table B carries value-level quality assessment",
        access_status="downloaded_new",
        license_or_terms="FAO-hosted workbook; project/reuse conditions need verification",
        foundation_model_role="small, high-documentation Southeast-Asian supplement",
        suitability="medium: useful Indonesian coverage with explicit quality companion, but old and small",
        limitations="Must not be used to overwrite a newer Indonesian national source if one becomes available; record-level source dependencies need audit.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Indonesia_070813_protected.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_indonesia_values.xlsx; data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_indonesia_quality.xlsx",
    ),
    source(
        source_key="smiling_laos_2013",
        name="SMILING Food Composition Table for Laos 2013",
        region="Asia",
        countries_or_coverage="Lao PDR",
        scope="national_core_quality_annotated",
        data_kind="quantitative nutrient composition plus value-level references and quality assessment",
        reported_foods="140",
        reported_components="not re-counted in this inventory",
        measurement_provenance="SMILING project table A has value references; table B carries value-level quality assessment",
        access_status="downloaded_new",
        license_or_terms="FAO-hosted workbook; project/reuse conditions need verification",
        foundation_model_role="small, high-documentation Southeast-Asian supplement",
        suitability="medium: adds otherwise scarce Lao coverage; requires currentness review",
        limitations="Small source and older release; later training use requires a source and component-definition audit.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Laos_010813_protected.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_laos_values.xlsx; data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_laos_quality.xlsx",
    ),
    source(
        source_key="smiling_thailand_2013",
        name="SMILING Food Composition Table for Thailand 2013",
        region="Asia",
        countries_or_coverage="Thailand",
        scope="national_core_quality_annotated",
        data_kind="quantitative nutrient composition plus value-level references and quality assessment",
        reported_foods="142",
        reported_components="not re-counted in this inventory",
        measurement_provenance="SMILING project table A has value references; table B carries value-level quality assessment",
        access_status="downloaded_new",
        license_or_terms="FAO-hosted workbook; project/reuse conditions need verification",
        foundation_model_role="historical quality-annotated Thai reference, not a substitute for Thai FCD 2025",
        suitability="medium for provenance methods; low incremental value if newer Thai FCD is licensed",
        limitations="Likely overlaps the national Thai source; retain as a separately versioned historical table rather than count it as independent food evidence.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Thailand_150513_protected.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_thailand_values.xlsx; data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_thailand_quality.xlsx",
    ),
    source(
        source_key="smiling_vietnam_2013",
        name="SMILING Food Composition Table for Vietnam 2013",
        region="Asia",
        countries_or_coverage="Viet Nam",
        scope="national_core_quality_annotated",
        data_kind="quantitative nutrient composition plus value-level references and quality assessment",
        reported_foods="162",
        reported_components="not re-counted in this inventory",
        measurement_provenance="SMILING project table A has value references; table B carries value-level quality assessment",
        access_status="downloaded_new",
        license_or_terms="FAO-hosted workbook; project/reuse conditions need verification",
        foundation_model_role="small, high-documentation Southeast-Asian supplement",
        suitability="medium: provides value-level documentation; later compare with newer Vietnamese source releases",
        limitations="Old and small; source and food-facet definitions remain necessary for future use.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Vietnam_180713_protected.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_vietnam_values.xlsx; data/raw/global_fcdb_inventory_2026_09_10/downloads/smiling_vietnam_quality.xlsx",
    ),
    source(
        source_key="sri_lanka_fcdb",
        name="Sri Lankan Food Composition Database",
        region="Asia",
        countries_or_coverage="Sri Lanka",
        scope="national_core",
        data_kind="quantitative nutrients including cooked foods",
        reported_foods="not stated on official directory landing page",
        reported_components="not stated on official directory landing page",
        measurement_provenance="country-specific FCDB and online searchable tool",
        access_status="free_searchable_web_tool_no_bulk_export_found",
        license_or_terms="terms require confirmation",
        foundation_model_role="South-Asian coverage candidate",
        suitability="medium: contemporary local-food coverage; needs raw export and provenance audit",
        limitations="A searchable tool alone is insufficient for a reproducible corpus; do not scrape it or infer a licence.",
        official_url="https://www.foodcompositiondb.lk/",
        download_url="https://www.foodcompositiondb.lk/",
        local_raw_path="",
    ),
    source(
        source_key="philfct_2019",
        name="Philippine Food Composition Tables Online Database (PhilFCT)",
        region="Asia",
        countries_or_coverage="Philippines",
        scope="national_core",
        data_kind="quantitative proximates, carbohydrates, vitamins, minerals and lipids",
        reported_foods="about 1,500",
        reported_components="not stated on official landing page",
        measurement_provenance="Philippine Food and Nutrition Research Institute database",
        access_status="searchable_web_tool_individual_reports_only",
        license_or_terms="copyrighted government database; bulk terms require permission",
        foundation_model_role="Southeast-Asian candidate",
        suitability="medium: strong local coverage but no reproducible bulk release",
        limitations="Official response explicitly states the online table is not downloadable; individual reports do not constitute a safe bulk acquisition route.",
        official_url="https://i.fnri.dost.gov.ph/login/fct",
        download_url="https://i.fnri.dost.gov.ph/login/fct",
        local_raw_path="",
    ),
    source(
        source_key="asean_fcdb_2014",
        name="ASEAN Food Composition Database Electronic Version 1 (2014)",
        region="Asia",
        countries_or_coverage="ASEAN member countries",
        scope="regional_nutrient_database",
        data_kind="quantitative nutrients",
        reported_foods="not confirmed in this inventory",
        reported_components="not confirmed in this inventory",
        measurement_provenance="ASEANFOODS regional compilation",
        access_status="catalogued_officially_no_current_bulk_endpoint_verified",
        license_or_terms="terms unknown",
        foundation_model_role="regional coverage catalogue candidate",
        suitability="medium potential but not ready",
        limitations="Older regional compilation; requires a current official downloadable copy plus lineage audit to avoid duplicating constituent national tables.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/asia/en/",
        download_url="",
        local_raw_path="",
    ),
    source(
        source_key="afaci_asian_fcdb",
        name="AFACI Asian Food Composition Database Project",
        region="Asia",
        countries_or_coverage="Bangladesh, Bhutan, Cambodia, Indonesia, Kyrgyzstan, Lao PDR, Mongolia, Myanmar, Nepal, Philippines, Sri Lanka, Thailand and Viet Nam",
        scope="regional_nutrient_database",
        data_kind="national and regional food nutrient/composition information under the AFACI project",
        reported_foods="not stated in the project page",
        reported_components="not stated in the project page",
        measurement_provenance="Asian Food and Agriculture Cooperation Initiative project; participating-country provenance must be captured before use",
        access_status="official_project_reports_download_availability_versioned_bulk_endpoint_not_verified",
        license_or_terms="not confirmed in this inventory",
        foundation_model_role="high-geographic-value Asian candidate after acquisition of a versioned database export and country-level lineage audit",
        suitability="medium: broad Asian partner coverage, but current download endpoint, value documentation and overlap with country tables are unverified",
        limitations="A project page is not an analyte-level data release. Do not count it as independent of Bangladesh, SMILING, Thai, Philippine or other constituent national sources until the underlying data and provenance are obtained.",
        official_url="https://rda.go.kr/afaci/site/project/view?pageId=02020600&pageName=GAP",
        download_url="https://koreanfood.rda.go.kr/",
        local_raw_path="",
    ),
    source(
        source_key="wafct_2019",
        name="FAO/INFOODS Food Composition Table for Western Africa 2019",
        region="Africa",
        countries_or_coverage="Benin, Burkina Faso, Gambia, Ghana, Guinea, Mali, Niger, Nigeria and Senegal",
        scope="regional_core",
        data_kind="quantitative nutrients, fatty acids, amino acids and related composition data",
        reported_foods="1,028 food codes in the downloaded summary sheet before source-type filtering",
        reported_components="57-component summary sheet; components catalogue has 57 main-component definitions",
        measurement_provenance="FAO/INFOODS table with source bibliography, analytical values and calculated mixed dishes",
        access_status="downloaded_new",
        license_or_terms="FAO free-access electronic file; cite the source and preserve source terms",
        foundation_model_role="primary Africa regional source; split analytical and calculated dish layers in any later construction",
        suitability="high geographic value and excellent component/source documentation",
        limitations="Contains recipe-derived profiles alongside source values; mixed dishes cannot be used as independent analytical validation labels.",
        official_url="https://www.fao.org/food-composition/tables-and-databases/detail/food-composition-tables/en",
        download_url="https://www.fao.org/fileadmin/user_upload/faoweb/2020/WAFCT_2019.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/wafct_2019.xlsx",
    ),
    source(
        source_key="lesotho_fct_2006",
        name="Lesotho Food Composition Table 2006",
        region="Africa",
        countries_or_coverage="Lesotho",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="443 six-digit food codes in the downloaded original-source sheet",
        reported_components="119 original-source sheet columns, including metadata and composition",
        measurement_provenance="FAO/INFOODS-catalogued national table",
        access_status="downloaded_new",
        license_or_terms="terms not stated in source workbook; use as a documented candidate pending licence review",
        foundation_model_role="Southern-Africa candidate source",
        suitability="medium: machine-readable official-directory workbook, but old and needs value-level documentation assessment",
        limitations="2006 release; no automatic training admission until licence, method and source details are audited.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/africa/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/LesFCT_final_copyrevised1.xlsm",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/lesotho_fct_2006.xlsm",
    ),
    source(
        source_key="ethiopian_fct_2025",
        name="Ethiopian Food Composition Table 2025",
        region="Africa",
        countries_or_coverage="Ethiopia",
        scope="national_core",
        data_kind="quantitative nutrient composition with food- and value-level documentation",
        reported_foods="727 food entries: 369 raw, 213 cooked and 145 mixed-ingredient dishes",
        reported_components="69 components in the full Excel datasheets; 39 in the condensed user table",
        measurement_provenance="Ethiopian Public Health Institute/FAO table with BiblioID, value documentation, n/min/max/SD/median where applicable, and FoodEx2 codes",
        access_status="official_user_guide_downloaded_full_excel_datasheets_to_be_obtained",
        license_or_terms="FAO/EPHI free-access publication; preserve release-specific attribution and terms",
        foundation_model_role="high-priority East-Africa core source after acquisition of the full value-documented Excel datasheets",
        suitability="high: current national release, explicit food/value documentation and FoodEx2 coding",
        limitations="The user guide is a condensed PDF. The full Excel datasheets are required before numeric ingestion; 145 mixed dishes and calculated values must remain a derived-dish layer.",
        official_url="https://www.fao.org/food-composition/tables-and-databases/detail/ethiopian-food-comporition-table/en",
        download_url="https://openknowledge.fao.org/handle/20.500.14283/cd9308en",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/ethiopian_fct_2025_user_guide.pdf",
    ),
    source(
        source_key="kenya_fct_2018",
        name="Kenya Food Composition Tables 2018",
        region="Africa",
        countries_or_coverage="Kenya",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="not re-counted in this inventory",
        reported_components="not re-counted in this inventory",
        measurement_provenance="FAO/INFOODS-linked national food composition table",
        access_status="downloaded_new_pdf_only",
        license_or_terms="official PDF; machine-extraction and reuse terms require assessment",
        foundation_model_role="East-Africa source candidate",
        suitability="medium: recent official table but currently unstructured",
        limitations="PDF alone must not be converted by unvalidated OCR into model labels; seek native data or conduct audited double extraction.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/africa/en/",
        download_url="https://www.fao.org/3/I8897EN/i8897en.pdf",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/kenya_fct_2018.pdf",
    ),
    source(
        source_key="malawi_fct_2019",
        name="Malawian Food Composition Table 2019",
        region="Africa",
        countries_or_coverage="Malawi",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="not re-counted in this inventory",
        reported_components="not re-counted in this inventory",
        measurement_provenance="MAFOODS national table catalogued by FAO/INFOODS",
        access_status="downloaded_new_pdf_only",
        license_or_terms="repository PDF; reuse terms require confirmation",
        foundation_model_role="Southern-Africa source candidate",
        suitability="medium: contemporary local-food table, not machine-ready",
        limitations="PDF-only source requires a validated extraction and provenance review before values can be used.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/africa/en/",
        download_url="https://dl.tufts.edu/downloads/g158bw806?filename=d217r336d.pdf",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/malawi_fct_2019.pdf",
    ),
    source(
        source_key="mozambique_fcdb_v2",
        name="Food Composition Database for Mozambique Version 2 (2011)",
        region="Africa",
        countries_or_coverage="Mozambique",
        scope="national_core",
        data_kind="quantitative nutrient composition",
        reported_foods="205",
        reported_components="35 nutrients",
        measurement_provenance="University of Helsinki/Mozambique food composition table",
        access_status="official_pdf_link_access_control_blocked_in_this_collection_run",
        license_or_terms="repository PDF; reuse terms require confirmation",
        foundation_model_role="Southern-Africa source candidate",
        suitability="medium: explicit food/nutrient coverage, but only PDF release located",
        limitations="The current direct PDF route returned an access-control page rather than a PDF in this collection run. Obtain the original file manually, then use it only after audited value extraction.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/africa/en/",
        download_url="https://helda.helsinki.fi/bitstream/handle/10138/337295/Food_composition_tables_for_Mozambique.pdf?sequence=1",
        local_raw_path="",
    ),
    source(
        source_key="nigeria_food_database",
        name="Nigeria Food Database 2019",
        region="Africa",
        countries_or_coverage="Nigeria",
        scope="national_core",
        data_kind="quantitative food composition",
        reported_foods="not stated in this inventory",
        reported_components="not stated in this inventory",
        measurement_provenance="Nigerian national web database listed by FAO/INFOODS",
        access_status="searchable_web_tool_no_verified_bulk_export",
        license_or_terms="terms unknown",
        foundation_model_role="West-Africa supplement candidate",
        suitability="medium potential; overlap with WAFCT must be resolved by provenance",
        limitations="No stable export was verified; do not scrape or count it as independent evidence until source ownership and download terms are clear.",
        official_url="http://nigeriafooddata.ui.edu.ng/",
        download_url="",
        local_raw_path="",
    ),
    source(
        source_key="safoods_2024",
        name="South African Food Data System / Food Composition Tables 6th Edition",
        region="Africa",
        countries_or_coverage="South Africa",
        scope="national_core",
        data_kind="quantitative nutrients",
        reported_foods="1,857",
        reported_components="36 nutrients in paid 6th-edition table; public search exposes 5",
        measurement_provenance="South African Medical Research Council national FCDB; source references stored per value",
        access_status="paid_or_permission_required",
        license_or_terms="electronic publication purchase required",
        foundation_model_role="high-value Southern-Africa candidate after institutional licence",
        suitability="high scientific relevance; not currently reproducibly downloadable",
        limitations="Public interface exposes only energy, carbohydrate, protein, lipids and fibre; full table is paid and contains both local and borrowed values.",
        official_url="https://safoods.mrc.ac.za/products.html",
        download_url="https://safoods.mrc.ac.za/composition.html",
        local_raw_path="",
    ),
    source(
        source_key="tbca_7",
        name="Brazilian Food Composition Table (TBCA)",
        region="Latin America",
        countries_or_coverage="Brazil",
        scope="national_core",
        data_kind="quantitative nutrients, biodiversity foods and calculated dishes",
        reported_foods="more than 5,700 foods in version 7.2; more than 4,000 preparations",
        reported_components="34 components for the intake-assessment dataset in version 6; current full count not fixed in this inventory",
        measurement_provenance="BRASILFOODS/USP compilation with food detail, mean/SD/range, methods and samples requested for submitted values",
        access_status="publicly_searchable_but_bulk_and_derivative_use_restricted",
        license_or_terms="CC BY-NC-ND 4.0 stated by the database",
        foundation_model_role="Brazilian coverage reference and possible licensed research source",
        suitability="high nutrition relevance; unsuitable for an openly redistributed, transformed training corpus without permission",
        limitations="No-derivatives condition prohibits the transformation required for harmonized training releases; preparations and brands must be held separately.",
        official_url="https://www.tbca.net.br/",
        download_url="https://www.tbca.net.br/base-dados-en/food_composition_personalized.php",
        local_raw_path="",
    ),
    source(
        source_key="sara_argentina",
        name="Argentina Sistema de Análisis y Registro de Alimentos (SARA)",
        region="Latin America",
        countries_or_coverage="Argentina",
        scope="national_core",
        data_kind="quantitative food composition",
        reported_foods="not stated in this inventory",
        reported_components="not stated in this inventory",
        measurement_provenance="Argentine Ministry of Health software/database",
        access_status="official_installer_available_terms_and_export_review_required",
        license_or_terms="terms not confirmed",
        foundation_model_role="Latin-American candidate after versioned machine-readable extraction and licence review",
        suitability="medium: official system but not a transparent data download",
        limitations="Software installer is not equivalent to a documented data release; do not ingest proprietary database contents without explicit permission.",
        official_url="https://sses.msal.gov.ar/sara/",
        download_url="https://sses.msal.gov.ar/sara/",
        local_raw_path="",
    ),
    source(
        source_key="latinfoods_tables",
        name="LATINFOODS national and regional food composition tables",
        region="Latin America",
        countries_or_coverage="Argentina, Brazil, Chile, Colombia, Costa Rica, Mexico, Peru and other Latin American countries",
        scope="directory_and_source_collection",
        data_kind="quantitative nutrient and selected phytochemical tables",
        reported_foods="varies by constituent source",
        reported_components="varies by constituent source",
        measurement_provenance="FAO/INFOODS directory links to national tables with variable methods",
        access_status="mixed_pdf_web_and_contact_only",
        license_or_terms="source-specific",
        foundation_model_role="discovery registry, not a single independent data source",
        suitability="important coverage map; each constituent source requires individual assessment",
        limitations="Many sources are PDFs, printed books or old web pages; never ingest this directory as a database or assume uniform licence/provenance.",
        official_url="https://www.fao.org/infoods/infoods/tables-and-databases/latin-america/en/",
        download_url="",
        local_raw_path="",
    ),
    source(
        source_key="anfood_2_0",
        name="FAO/INFOODS Analytical Food Composition Database AnFooD 2.0",
        region="Global",
        countries_or_coverage="Multiple countries",
        scope="global_specialist_analytical",
        data_kind="quantitative analytical food-composition data",
        reported_foods="1,962 unique food item IDs across downloaded food-group sheets",
        reported_components="up to 245 columns in workbook sheets",
        measurement_provenance="carefully reviewed analytical data; FAO states no added estimation, imputation or calculation for missing values",
        access_status="downloaded_new",
        license_or_terms="FAO free-access electronic file; cite source",
        foundation_model_role="high-quality specialist analytical layer and external plausibility reference",
        suitability="high value-level analytical evidence; less suitable as a broad food-name corpus because coverage is sparse and publication-derived",
        limitations="Do not collapse replicate literature measurements into food-level labels without retaining method, location, cultivar and publication provenance.",
        official_url="https://www.fao.org/food-composition/tables-and-databases/detail/%28global--2017%29-fao-infoods-analytical-food-composition-database---version-2.0-%28anfood2.0%29/en",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/AnFooD2.0.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/anfood_2_0.xlsx",
    ),
    source(
        source_key="biofoodcomp_4_0",
        name="FAO/INFOODS Food Composition Database for Biodiversity BioFoodComp 4.0",
        region="Global",
        countries_or_coverage="Multiple countries and biodiversity foods",
        scope="global_specialist_analytical",
        data_kind="quantitative analytical food-composition data",
        reported_foods="10,129 unique food item IDs across downloaded food-group sheets",
        reported_components="up to 247 columns in workbook sheets",
        measurement_provenance="published and unpublished analytical literature compiled for food biodiversity",
        access_status="downloaded_new",
        license_or_terms="FAO free-access electronic file; cite source",
        foundation_model_role="biodiversity and cultivar-aware specialist layer",
        suitability="high for long-tail food diversity and analytical variability; not a replacement for national consumption tables",
        limitations="Multiple varieties/breeds/locations are intentional distinct observations; do not merge them by common name.",
        official_url="https://www.fao.org/infoods/infoods/food-biodiversity/en/",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/BioFoodComp4.0.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/biofoodcomp_4_0.xlsx",
    ),
    source(
        source_key="phyfoodcomp_1_0",
        name="FAO/INFOODS/IZiNCG Global Food Composition Database for Phytate PhyFoodComp 1.0",
        region="Global",
        countries_or_coverage="Multiple countries",
        scope="global_specialist_analytical",
        data_kind="quantitative phytate forms, iron, zinc, calcium, water and phytate:mineral ratios",
        reported_foods="3,377 unique food item IDs across downloaded food-group sheets",
        reported_components="35 component definitions in the source documentation",
        measurement_provenance="analytical data with method and bibliography context",
        access_status="downloaded_new",
        license_or_terms="FAO free-access electronic file; cite source",
        foundation_model_role="specialist anti-nutrient/mineral-bioavailability layer",
        suitability="high for targeted phytate research; too narrow to serve as a general nutrition corpus",
        limitations="Phytate chemical form and assay method are central; not interchangeable with generic phosphorus or total nutrient labels.",
        official_url="https://www.fao.org/food-composition/tables-and-databases/detail/%28global--2018%29-fao-infoods-izincg-global-food-composition-database-for-phytate---version-1.0-%28phyfoodcomp1.0%29/en",
        download_url="https://www.fao.org/fileadmin/templates/food_composition/documents/PhyFoodComp_1.0.xlsx",
        local_raw_path="data/raw/global_fcdb_inventory_2026_09_10/downloads/phyfoodcomp_1_0.xlsx",
    ),
    source(
        source_key="foodb_2020",
        name="FooDB 1.0",
        region="Global",
        countries_or_coverage="Common foods with food-chemical associations from multiple source databases and literature",
        scope="global_specialist_metabolite",
        data_kind="food chemicals, nutrients, metabolites, flavour/aroma compounds and source links",
        reported_foods="not re-counted in this inventory; local raw release retained",
        reported_components="not re-counted in this inventory; extensive chemical catalogue",
        measurement_provenance="secondary aggregation; individual values may be copied from USDA, Frida, Phenol-Explorer or literature",
        access_status="already_local",
        license_or_terms="CC BY-NC 4.0",
        foundation_model_role="specialist chemical-identity and literature-provenance layer, not independent numeric evidence",
        suitability="high for chemical vocabulary and source discovery; low as an independent quantitative validation source",
        limitations="Must trace each numeric value to its originating source and avoid counting re-published values as new observations; non-commercial licence limits release strategy.",
        official_url="https://foodb.ca/about",
        download_url="https://foodb.ca/downloads",
        local_raw_path="foodb_2020_04_07_csv",
    ),
    source(
        source_key="phenol_explorer",
        name="Phenol-Explorer",
        region="Global",
        countries_or_coverage="Multiple countries and foods",
        scope="global_specialist_metabolite",
        data_kind="quantitative food polyphenol composition",
        reported_foods="459 foods",
        reported_components="501 polyphenols across 6 classes and 31 subclasses",
        measurement_provenance="literature-curated polyphenol composition database",
        access_status="web_export_advertised_bulk_snapshot_not_collected",
        license_or_terms="terms require confirmation before bulk use",
        foundation_model_role="polyphenol specialist layer after bulk export and licence check",
        suitability="high chemical specificity; narrow food/metabolite support and not a general nutrient source",
        limitations="Retention, processing, glycoside definition and assay basis must remain explicit; no automatic match to FooDB chemical names.",
        official_url="https://phenol-explorer.eu/compounds",
        download_url="https://phenol-explorer.eu/foods",
        local_raw_path="",
    ),
    source(
        source_key="ebasis",
        name="EuroFIR eBASIS",
        region="Europe",
        countries_or_coverage="European plant foods",
        scope="specialist_metabolite",
        data_kind="bioactive constituents and biological-effect evidence",
        reported_foods="over 300 major European plant foods",
        reported_components="about 200 beneficial and 90 toxic bioactive compounds across 24 classes",
        measurement_provenance="critically evaluated peer-reviewed data with EuroFIR quality procedures",
        access_status="restricted_individual_login",
        license_or_terms="individual account required",
        foundation_model_role="high-quality specialist candidate under data-use agreement",
        suitability="high scientific quality, not currently reproducible as an open download",
        limitations="Do not use user-level web access to create an undisclosed data dump; obtain an explicit research agreement.",
        official_url="https://ebasis.eurofir.org/",
        download_url="https://www.eurofir.org/our-tools/ebasis/",
        local_raw_path="",
    ),
]


DOWNLOADS = {
    "bangladesh_fct_2013.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCDB_7_4_14.xlsx",
    "smiling_cambodia_values.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT__Cambodia_010813_protected.xlsx",
    "smiling_cambodia_quality.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5b_SMILING_FCT_QA_Cambodia_010813.xlsx",
    "smiling_indonesia_values.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Indonesia_070813_protected.xlsx",
    "smiling_indonesia_quality.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5b_SMILING_FCT_QA_Indonesia_070813.xlsx",
    "smiling_laos_values.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Laos_010813_protected.xlsx",
    "smiling_laos_quality.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5b_SMILING_FCT_QA_Laos_010813.xlsx",
    "smiling_thailand_values.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Thailand_150513_protected.xlsx",
    "smiling_thailand_quality.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5b_SMILING_FCT_QA_Thailand_150513.xlsx",
    "smiling_vietnam_values.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5a_SMILING_FCT_Vietnam_180713_protected.xlsx",
    "smiling_vietnam_quality.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/FCT_SMILING_PROJECT_ASIA/D3_5b_SMILING_FCT_QA_Vietnam_180713.xlsx",
    "wafct_2019.xlsx": "https://www.fao.org/fileadmin/user_upload/faoweb/2020/WAFCT_2019.xlsx",
    "lesotho_fct_2006.xlsm": "https://www.fao.org/fileadmin/templates/food_composition/documents/LesFCT_final_copyrevised1.xlsm",
    "kenya_fct_2018.pdf": "https://www.fao.org/3/I8897EN/i8897en.pdf",
    "malawi_fct_2019.pdf": "https://dl.tufts.edu/downloads/g158bw806?filename=d217r336d.pdf",
    "ethiopian_fct_2025_user_guide.pdf": "https://openknowledge.fao.org/server/api/core/bitstreams/22c422c5-4c66-4233-aa15-0cd6e6c47f6e/content",
    "mozambique_fcdb_v2_2011.pdf": "https://helda.helsinki.fi/bitstream/handle/10138/337295/Food_composition_tables_for_Mozambique.pdf?sequence=1",
    "anfood_2_0.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/AnFooD2.0.xlsx",
    "biofoodcomp_4_0.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/BioFoodComp4.0.xlsx",
    "phyfoodcomp_1_0.xlsx": "https://www.fao.org/fileadmin/templates/food_composition/documents/PhyFoodComp_1.0.xlsx",
    "swiss_fcdb_v7_1.xlsx": "https://naehrwertdaten.ch/wp-content/uploads/2026/07/Base_de_donnees_suisse_des_valeurs_nutritives.xlsx",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def valid_artifact(path: Path) -> bool:
    """Reject HTML error pages masquerading as a spreadsheet or PDF download."""
    header = path.read_bytes()[:8]
    suffix = path.suffix.lower()
    if suffix == ".pdf":
        return header.startswith(b"%PDF-")
    if suffix in {".xlsx", ".xlsm"}:
        return header.startswith(b"PK\x03\x04")
    return path.stat().st_size > 0


def download(url: str, destination: Path) -> dict[str, Any]:
    request = urllib.request.Request(url, headers={"User-Agent": "FoodNutritionSourceInventory/1.0 (research use)"})
    try:
        with urllib.request.urlopen(request, timeout=120) as response, destination.open("wb") as handle:
            shutil.copyfileobj(response, handle)
        if not valid_artifact(destination):
            destination.unlink(missing_ok=True)
            return {
                "status": "invalid_artifact",
                "url": url,
                "detail": "Response did not match the expected file signature; likely an access-control or error page.",
            }
        return {
            "status": "downloaded",
            "url": url,
            "path": str(destination.relative_to(ROOT)),
            "bytes": destination.stat().st_size,
            "sha256": sha256(destination),
        }
    except urllib.error.HTTPError as error:
        destination.unlink(missing_ok=True)
        return {"status": "http_error", "url": url, "http_status": error.code, "detail": str(error)}
    except urllib.error.URLError as error:
        destination.unlink(missing_ok=True)
        return {"status": "url_error", "url": url, "detail": str(error.reason)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--download", action="store_true", help="Download directly accessible raw source artifacts.")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat()

    manifest: list[dict[str, Any]] = []
    for filename, url in DOWNLOADS.items():
        destination = DOWNLOAD_DIR / filename
        if destination.exists() and valid_artifact(destination):
            manifest.append(
                {
                    "status": "already_present",
                    "url": url,
                    "path": str(destination.relative_to(ROOT)),
                    "bytes": destination.stat().st_size,
                    "sha256": sha256(destination),
                }
            )
        elif destination.exists():
            destination.unlink()
            manifest.append(
                {
                    "status": "invalid_existing_artifact_removed",
                    "url": url,
                    "path": str(destination.relative_to(ROOT)),
                    "detail": "Existing file did not match the expected file signature.",
                }
            )
        elif args.download:
            manifest.append(download(url, destination))
        else:
            manifest.append({"status": "not_requested", "url": url, "path": str(destination.relative_to(ROOT))})

    fields = list(SOURCES[0].keys())
    with (OUT_DIR / "source_registry.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(SOURCES)

    (OUT_DIR / "source_registry.json").write_text(
        json.dumps({"as_of_utc": now, "no_merging_performed": True, "sources": SOURCES}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (OUT_DIR / "download_manifest.json").write_text(
        json.dumps({"as_of_utc": now, "no_merging_performed": True, "files": manifest}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(SOURCES)} source registry entries to {OUT_DIR}")
    print(f"Direct artifact records: {len(manifest)}")


if __name__ == "__main__":
    main()
